### ISSUE TITLE
Mods that manipulate chat breaks integration/chat functionality

### ISSUE THREAD

**Issue by X-Niter** [ErdbeerbaerLP/DiscordIntegration-Fabric#5]
Mod version: 2.3.6-1.18.1
Fabric Version: 0.12.12
FTB Ranks version: 1801.1.6-build.20.jar (Only 1.18 fabric version)

Everything works as intended with the whole mod aside from Chat relay Minecraft chat to Discord. 

Taking FTB Ranks out fixes the issue, and digging through their mod it looks like they do in fact do some chat styling and formating, specifically the java class "FTBRanksAPIImpl.class" on line 104.

I know you have a note about the next update working with the mod StyledChat, however, any interest in getting it to work with FTB ranks?

**Comment by ErdbeerbaerLP** [comment]
I will look what I can do

**Comment by LiaungYip** [comment]
For the record, this mod (FTB Ranks) is included in All Of Fabric 5 and causes the same issue when used with that pack.

**Comment by X-Niter** [comment]
Updating the issue name as I'm noticing the issue doesn't come down to one mod, but any of which manipulate the chat functionality causing the integration or chat system to break in different ways. 

FTB Ranks > Game to discord chat INOP
Collective > Game to discord chat INOP
Player roles or whatever it's called > Blocks players from sending chat completly. 

I also want to add, this is not per say an issue on Erd's part, it's an issue with any discord integration mod and I've tried a lot of them over the past few weeks already. 
The issue comes down to however these mods are manipulating the chat and then sending it out, then trying to figure out how to actually capture it properly to either relay to discord or even allow messages to pass through so players still see it. 
Spent about 2 weeks on Erb's code and FTB ranks trying to figure out if I could get any success but I quickly got annoyed trying to figure out fabrics's api.

**Comment by ErdbeerbaerLP** [comment]
Since this issue existed, an config option to fix this has been added. Closing.
